-- MySQL Script generated by MySQL Workbench
-- Sat Jul 24 22:31:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LaIsabelaHospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LaIsabelaHospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LaIsabelaHospital` DEFAULT CHARACTER SET utf8 ;
USE `LaIsabelaHospital` ;

-- -----------------------------------------------------
-- Table `LaIsabelaHospital`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LaIsabelaHospital`.`pacientes` (
  `cedula` INT NOT NULL AUTO_INCREMENT,
  `primer-nombre` VARCHAR(45) NOT NULL,
  `segundo-nombre` VARCHAR(45) NULL,
  `primer-apellido` VARCHAR(45) NOT NULL,
  `segundo-apellido` VARCHAR(45) NOT NULL,
  `ano-nacimiento` INT NOT NULL,
  `numero-historiaclinica` VARCHAR(45) NOT NULL,
  `numero-asegurado` INT NOT NULL,
  `tipo-seguro` VARCHAR(45) NOT NULL,
  `nombre-padre` VARCHAR(45) NOT NULL,
  `nombre-madre` VARCHAR(45) NOT NULL,
  `apellido-padre` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
